### ISSUE TITLE
"filter -> sorted by latest"not working

### ISSUE THREAD

**Issue by Pancakes0** [CarlosEsco/Neko#993] opened 2022-06-07 14:31 UTC
### Steps to reproduce

1. -> Browse tab -> filter button
2. sort by: latest uploaded chapter -> click filter

### Expected behavior

expectation: showing me manga sorted by; 'the latest uploaded chapter'.

### Actual behavior

problem: doesnt show me manga sorted by 'the latest uploaded chapter'.

### Crash logs

[2022-06-07-release.txt](https://github.com/CarlosEsco/Neko/files/8860870/2022-06-07-release.txt)

### Neko version

Stable 2.9.1.1 

### Android version

Android 12

### Device

Realme 9 Pro+

### Other details

video:
https://user-images.githubusercontent.com/73923883/172404859-e4602fc8-5bc4-40e4-9d87-91f9b7877603.mp4

Q. "why not use the latest button?"
A. because i want to be able to filter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2022-06-07 16:19
Can you dump a crashlog in the advanced settings

**Comment by Pancakes0** [comment] 2022-06-08 10:57
ah yes i can, i did that yesterday. i left it out since it says if im experiencing crashes sorry

**Comment by CarlosEsco** [comment] 2022-06-08 11:04
It looks like you are having connection issues with mangadex.

```Error trying to search Unable to resolve host "api.mangadex.org": No address associated with hostname java.net.UnknownHostException: Unable to resolve host "api.mangadex.org": No address associated with hostname```

**Comment by Pancakes0** [comment] 2022-06-09 06:40
hmm... that is super weird (more like i dont understand). everything else loads perfectly fine, it was a smooth experience. 
just that one button........... 

https://drive.google.com/file/d/148g-aHsSjL_0nIqTn4zYwWCUj29z3j4i/view?usp=sharing
(i forgot i was using 3g network instead of wifi so its a lot slower. i tried changing connection between them, sorting by latest still doesnt work)

mangadex website connected was fine.... 
is there a way to fix this?

**Comment by cookie1111** [comment] 2022-06-11 22:19
Experiencing the same issue

**Comment by cookie1111** [comment] 2022-06-12 09:21
Checked a bit further and it seems the issue is on mangadex since the feature doesnt work on their site either

**Comment by CarlosEsco** [comment] 2022-09-16 19:02
there was a bug with this, its fixed in 2.10.11

**Closed by CarlosEsco** 2022-09-16 19:02 UTC
Labels: bug, Fixed in Future release
