### ISSUE TITLE
[Bug] Chapter load hangs occasionally and makes the app non-functional

### ISSUE THREAD

**Issue by Jeglet** [CarlosEsco/Neko#521] opened 2021-06-27 13:37 UTC
### Device information
* Tachiyomi version: 2.5.0
* Android phone & version: A11, S20U

## Steps to reproduce
1. Read chapters until one hangs
2. Try to use the rest of the app

### Expected behavior
Chapter should load and various app functions should work

### Actual behavior
Chapter doesn't load and many features of the app stop functioning

### Other details
https://cloud.heckin.how/s/sLyEQNHnma5ejBJ video of issue

**Comment by CarlosEsco** [comment] 2021-06-29 20:01
It's slightly better in 2.5.1 but i could not get this fixed, don't know whats causing it tbh

**Comment by CountofUndolpho** [comment] 2021-07-01 12:11
I don't know if this helps but for me in 2.5.0 it would hang on a blank screen but in 2.5.1 it hangs on a white page that's blank apart from the page number.

**Comment by CountofUndolpho** [comment] 2021-07-09 10:46
Me again! Since the api updated the crashing now starts when the cache is between 80 and 100 meg. I've checked it and reset it a dozen times and it's consistent.

**Comment by CarlosEsco** [comment] 2021-07-09 10:48
@CountofUndolpho so if you clear the cache it works fine once its too large?

**Comment by CountofUndolpho** [comment] 2021-07-09 13:23
Clear the cache and force a restart it works fine until caching a chapter sends it over the trigger point. If I don't clear the cache but i do force a restart the crashes get closer together.

**Comment by spamtaztik** [comment] 2021-07-10 14:12
I can confirm that I am also faced with this issue, but in my case the app doesn't "crash". While reading the app would suddenly stop loading new pages (the loading animation keeps spinning and spinning without it ever becoming a full circle). I have to force close the app, clear cache, and reopen it. After cache reaches about 30-40MB the issue would repeat. My phone has way more storage than 40MB, so this issue shouldn't have happened... Using Neko version 2.5.2.

**Comment by CountofUndolpho** [comment] 2021-07-11 13:53
After the recent update to 2.5.3 the trigger has dropped to around 20 but doesn't seem as consistent. What an odd bug!

**Comment by CarlosEsco** [comment] 2021-07-13 02:12
I believe this is fixed in the next release.  I haven't been able to replicate it in the debug versions

**Comment by CountofUndolpho** [comment] 2021-07-13 03:45
Huzzah!

**Comment by CarlosEsco** [comment] 2021-07-14 22:23
in  5.2.4

**Closed by CarlosEsco** 2021-07-14 22:23 UTC
Labels: Fixed in Future release, bug

**Comment by Jeglet** [comment] 2021-07-15 01:19
Still an issue with 5.2.4, unfortunately.
