### ISSUE TITLE
Bugs and issues

### ISSUE THREAD

**Issue by ghenie123** [CarlosEsco/Neko#1506] opened 2023-08-08 04:00 UTC
### Steps to reproduce

the app immediately crash when open the app.

the "share logs" button on notification it crash too

and the "restart the application'' on the app crashes too

### Expected behavior

the app should be open fine without bugs or errors

### Actual behavior

when i exit the app after a second it brings me back to the app and it says on the top "An Unexpected Error Occurred" 
and when i pressed the "Restart the application" button it load for a while but its still crash.
the "Dump crush Logs'' button work and its popping a notification and open the logs work but when sharing it also crash the app.

### Crash logs

App version: 2.13.4 (standard, 397dc966c, 190, 2023-08-07T17:57:35.128344251)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.003 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 2120
Device model: V2134
Device product name: 2134T
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: java.lang.AbstractMethodError: abstract method "logcat.LogcatKt logcat.LogcatKt.setResponseCode$enumunboxing$0(int)"
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.readGenerateAuthTokenResponse(SourceFile:91)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(SourceFile:93)
at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(SourceFile:31)
at com.google.firebase.installations.FirebaseInstallations.$r8$lambda$Kl2wdAe5utVajeTmV5LyfWUz3Bo(SourceFile:105)
at com.google.firebase.installations.FirebaseInstallations$$ExternalSyntheticLambda0.run(SourceFile:1)
at com.google.firebase.concurrent.SequentialExecutor$1.run(SourceFile:9)
at com.google.firebase.concurrent.SequentialExecutor$1.workOnQueue(SourceFile:1)
at com.google.firebase.concurrent.SequentialExecutor$1.run(SourceFile:13)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at com.google.firebase.concurrent.CustomThreadFactory.$r8$lambda$25wFMnJXuxCXflRCTG3ggSOiDOE(SourceFile:13)
at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(SourceFile:15)
at java.lang.Thread.run(Thread.java:1012)

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************

### Neko version

2.13.4

### Android version

Android 12 

### Device

Vivo Y15A

### Other details

i tried other things like force stopping the app or clear the cache and restart my phone but its still the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2023-08-08 10:24
Duplicate of #1504

**Closed by CarlosEsco** 2023-08-08 10:24 UTC
Labels: bug
