### ISSUE TITLE
[Bug] No longer marking chapters as read.

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#211] opened 2020-05-19 22:00 UTC
### Device information
* Tachiyomi version: 2.0.10
* Android phone & version: Pixel 2 XL and android 10

## Steps to reproduce
1. read a chapter
2. go to mangadex, and that chapter isn't marked as read.

### Expected behavior
it should mark chapters as read

### Actual behavior
it is not updating those chapters as read.

### Other details
seems to just be the chapters having an issue. Because when i switch from `plan to read` to `reading`, that is updated in mangadex.

**Comment by CarlosEsco** [comment] 2020-05-20 00:11
This is by design.  As downloading a chapter was marking it read even if you didn't read.  I eventually plan to sync read to dex but want it to be deliberate and opt in

**Comment by CarlosEsco** [comment] 2020-05-20 00:11
This is by design.  As downloading a chapter was marking it read even if you didn't read.  I eventually plan to sync read to dex but want it to be deliberate and opt in

**Comment by CarlosEsco** [comment] 2020-05-20 00:11
To add the original marking as read was issue with their api.

**Closed by CarlosEsco** 2020-05-20 00:11 UTC
Labels: bug
