### ISSUE TITLE
Neko keeps crashing after turning on Lock with biometrics

### ISSUE THREAD

**Issue by wyz3r0** [CarlosEsco/Neko#679] opened 2021-09-13 12:12 UTC
After I updated Neko to 2.6.1 my app stopped working. I tried clearing cache, force stopping the app and restarting my phone (samsung galaxy s7, android 8.0.0). Then I redownloaded Neko and noticed that only when I turn on Lock with biometrics the app stops working.
![20210913_140620](https://user-images.githubusercontent.com/77502943/133080572-9c009452-9970-4ae7-aef3-a55151c59a42.jpg)

**Comment by CarlosEsco** [comment] 2021-09-13 12:37
Can you download j2k and see if it has the same issue?
https://github.com/Jays2Kings/tachiyomiJ2K/releases/tag/v1.3.0

**Comment by wyz3r0** [comment] 2021-09-13 13:09
Yep, I have the same issue with J2K but I don't get the 'keeps stopping' message. It just crashes instantly.

**Comment by Jays2Kings** [comment] 2021-09-13 23:06
@wyz3r0 can you download this apk and test if the issue is still happening after turning on biometrics
[Uploading tachij2k-sams8.0-fix.zip…]()

**Comment by CarlosEsco** [comment] 2021-09-16 13:45
fixed in latest release you will need to manually download from github to update

**Closed by CarlosEsco** 2021-09-16 13:45 UTC

**Comment by mrnoname1000** [comment] 2021-09-17 22:56
This still happens for me on Neko and J2K.

**Comment by CarlosEsco** [comment] 2021-09-17 22:57
> This still happens for me on Neko and J2K.

You manually updated to the newest versions released in the last couple days?

**Comment by mrnoname1000** [comment] 2021-09-18 09:07
Yes, Neko 2.6.2 and J2K 1.3.1.

**Comment by CarlosEsco** [comment] 2021-09-18 09:34
@Jays2Kings
