### ISSUE TITLE
Auto-tracking error

### ISSUE THREAD

**Issue by TheSeriousYoungBoy** [CarlosEsco/Neko#1333] opened 2023-02-06 14:05 UTC
### Steps to reproduce

Open Neko
Go to Library
Open a title
(Neko will now try to add a tracker for the current opened title)
Got an error
Try choosing "add tracker manually"
Again, an error.

### Expected behavior

Open Neko
Go to Library
Open a title
(Neko will now try to add a tracker for the current opened title)
Output: "tracker missing, please add it manually"

### Actual behavior

https://user-images.githubusercontent.com/119454295/216991798-49dea0d1-0b20-429b-b3e5-8a18ca1211eb.mp4

### Crash logs

None

### Neko version

2.12.7

### Android version

Android 12

### Device

Xiaomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2023-02-06 14:19
Can you dump a crashlog and see if it shows the error

**Comment by TheSeriousYoungBoy** [comment] 2023-02-06 14:31
> Can you dump a crashlog and see if it shows the error

There are no error logs even using the verbose logging.

**Comment by CarlosEsco** [comment] 2023-02-06 14:56
did you force close the app after enabling the verbose?

**Comment by TheSeriousYoungBoy** [comment] 2023-02-06 15:14
> did you force close the app after enabling the verbose?

I usually don't need to. If I simply remove it from the "recent apps", it will be "force close" automatically. I just tried it now and simply closing it normally stops the app.

**Comment by CarlosEsco** [comment] 2023-02-06 16:49
Can you try logging out of mal and then login again

**Comment by TheSeriousYoungBoy** [comment] 2023-02-06 16:59
> Can you try logging out of mal and then login again

Still the same error.

It says: "Error registering tracker"

Note: This might be a problem to something else entirely as the **tracker** itself seem to be fine from other titles or simply that sole series is the only problem?

**Comment by CarlosEsco** [comment] 2023-02-07 17:56
So the issue is it's `Pending Aproval`
https://myanimelist.net/manga/149604/Isekai_de_Uwamae_Hanete_Ikiteiku__Saisei_Mahou_Tsukai_no_Yuru_Fuwa_Jinzai_Haken_Seikatsu

**Comment by CarlosEsco** [comment] 2023-02-08 11:13
also the api doesn't tell you when this is the case either 😞

**Comment by CarlosEsco** [comment] 2023-04-18 14:06
closing since there is nothing i can do about it for now

**Closed by CarlosEsco** 2023-04-18 14:06 UTC
Labels: bug
