### ISSUE TITLE
[Bug] Image Decoding Error in Senko-san, Ch. 25, last page

### ISSUE THREAD

**Issue by moka491** [CarlosEsco/Neko#406] opened 2021-01-26 00:20 UTC
### Device information
* Neko version: 2.1.5.5
* Android phone & version: Pixel 3a, Android 11

## Steps to reproduce
1. Open Chapter 25 of "Sewayaki Kitsune no Senko-san"
2. Swipe or go to the last page of that chapter

### Expected behavior
Being able to read the last page correctly

### Actual behavior
The app force-crashes and restarts

### Other details
1. The page loads fine on Mangadex' website
2. It didnt help to download the chapter (although the download worked fine)
3  I attached a Logcat report of the error:
[Log_2021-01-26_01-08-35.txt](https://github.com/CarlosEsco/Neko/files/5870361/Log_2021-01-26_01-08-35.txt)

**Comment by CarlosEsco** [comment] 2021-01-26 12:46
Can you clear your chapter cache in advanced settings, then try?  I was unable to reproduce.  If it still happens you will need to enable extreme logging, force close the app then retry and then send me the log. (There is no useful info in the current log)

**Comment by moka491** [comment] 2021-01-26 13:12
Okay. Clearning chapter cache didn't help, so I created a network log
[2021-01-26-release.txt](https://github.com/CarlosEsco/Neko/files/5873448/2021-01-26-release.txt)

I did multiple attempts and looked at the logs. 
I see a 404 Manga not found error at the bottom, and multiple 404 Invalid Url Host errors a bit further up..

**Comment by moka491** [comment] 2021-01-26 16:36
Since I just recorded it anyway, here's also a screen recording that shows the issue: 
https://mega.nz/file/XFYDFYoK#Lg_73577rJR3nME_n0DbZPe0H_c2I4PgGmBR1EKBy_E

**Comment by moka491** [comment] 2021-01-26 19:02
Update: The same thing happens for me in Ch. 39 Page 3

**Comment by CarlosEsco** [comment] 2021-01-26 19:15
This is probably gonna be a bit hard to debug.
so 404 in your log is standard for MDList manga that you dont follow so thats nothing to worry about
the invalid host seems to be an issue with reporting mangadex.home back to mangadex (they want to know if an image is loaded from md@home successfully)

If i had to guess.  Maybe you are hitting a bad md@home host?

**Comment by moka491** [comment] 2021-01-26 19:24
Hmm, anything I could do to test this? I played around with some settings, like using a different image server, compressing the chapter pages and so on, but nothing helped to alleviate the issue.

I'll probably set up Android Studio and try to debug right on the device. If I find anything, I'll do a PR or write it here.

**Comment by CarlosEsco** [comment] 2021-01-26 19:43
if you are willing to go that far i definitely have some things to try.  These are all independent of each other

1 - remove manga from library clear chapter cache, and db.  re add then try to read
2 - disable md@home on dex site.  and do then repeat above
3 - clone app, build a debug version, try to get error

**Comment by moka491** [comment] 2021-01-26 21:00
While I followed all those 3 steps and couldn't fix the error that way, I noticed that it didn't occur with my own debug build, so I ended up just reinstalling the Stable apk and that fixed the error somehow ¯\\\_(ツ)_/¯

**Comment by moka491** [comment] 2021-01-26 21:03
Update: I enabled "crop borders" in the reader settings and THAT actually causes the issues on aforementioned pages. Try to reproduce it with that option enabled.

**Comment by CarlosEsco** [comment] 2021-01-26 21:07
Can you download tachiyomi preview and the dex extension and see if the crop border issue causes it in that app

**Comment by moka491** [comment] 2021-01-26 21:13
Yes. The issue also arises in Tachiyomi preview once I enable Crop Borders. 
So I should bring this issue up to the Tachiyomi devs?

**Comment by CarlosEsco** [comment] 2021-01-26 21:17
Yea can you open an issue on that repo, the crop border stuff was changed recently

**Comment by CarlosEsco** [comment] 2021-03-04 11:51
Should be fixed in newest release

**Closed by CarlosEsco** 2021-03-04 11:51 UTC
Labels: Fixed in Future release, bug
